name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload to FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: '${{ secrets.FTP_SERVER }}'
          user: '${{ secrets.FTP_USERNAME }}'
          password: '${{ secrets.FTP_PASSWORD }}'
          localDir: app
          remoteDir: .
          options: "--ascii"
